name: Project Issue

on:
  issues:
    types: [opened, reopened]

jobs:
  main:
    name: 'Run'
    uses: usf-cs272-spring2023/action-workflows/.github/workflows/project-issue.yml@main
    secrets: inherit