name: Project Review

on:
  pull_request_review:
    types: [submitted, edited]

jobs:
  main:
    name: 'Run'
    uses: usf-cs272-spring2023/cs272-workflows/.github/workflows/project-review.yml@main
    secrets: inherit